# Generated by Django 5.2.8 on 2025-11-21 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TbAlternatives",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("alternative_letter", models.CharField(max_length=1)),
                ("alternative_text", models.TextField()),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "descriptor_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Alternativa",
                "verbose_name_plural": "Alternativas",
                "db_table": "tb_alternatives",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TbAssessmentMetadata",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("application_type", models.CharField(max_length=50)),
                ("assessment_period", models.CharField(max_length=50)),
                ("fiscal_year", models.BigIntegerField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Metadado de Avaliação",
                "verbose_name_plural": "Metadados de Avaliações",
                "db_table": "tb_assessment_metadata",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TbCity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Cidade",
                "verbose_name_plural": "Cidades",
                "db_table": "tb_city",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TbClass",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("class_name", models.CharField(max_length=100)),
                ("school_year", models.IntegerField()),
                ("grade", models.CharField(blank=True, max_length=50, null=True)),
                ("shift", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Turma",
                "verbose_name_plural": "Turmas",
                "db_table": "tb_class",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TbClassIdebIndicators",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fiscal_year", models.BigIntegerField()),
                (
                    "class_ideb_target",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "expected_avg_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "actual_avg_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Indicador IDEB da Turma",
                "verbose_name_plural": "Indicadores IDEB das Turmas",
                "db_table": "tb_class_ideb_indicators",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TbCompetencyIdeb",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("subject", models.CharField(max_length=100)),
                ("competency_code", models.CharField(max_length=50, unique=True)),
                ("competency_name", models.CharField(max_length=500)),
                ("grade", models.CharField(max_length=10)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Competência IDEB",
                "verbose_name_plural": "Competências IDEB",
                "db_table": "tb_competency_ideb",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TbDescriptorsCatalog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("subject", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "learning_field",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("grade", models.CharField(blank=True, max_length=50, null=True)),
                ("descriptor_code", models.CharField(max_length=50, unique=True)),
                ("descriptor_name", models.CharField(max_length=255)),
                ("descriptor_description", models.TextField(blank=True, null=True)),
                ("icon", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Descritor",
                "verbose_name_plural": "Catálogo de Descritores",
                "db_table": "tb_descriptors_catalog",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TbExamApplications",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("application_date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("fiscal_year", models.IntegerField(blank=True, null=True)),
                ("status", models.CharField(default="scheduled", max_length=50)),
                ("observations", models.TextField(blank=True, null=True)),
                (
                    "application_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "assessment_period",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Aplicação de Exame",
                "verbose_name_plural": "Aplicações de Exames",
                "db_table": "tb_exam_applications",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TbExamResults",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "total_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("correct_answers", models.IntegerField(blank=True, null=True)),
                ("wrong_answers", models.IntegerField(blank=True, null=True)),
                ("blank_answers", models.IntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Resultado do Exame",
                "verbose_name_plural": "Resultados dos Exames",
                "db_table": "tb_exam_results",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TbExams",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("exam_code", models.CharField(max_length=50, unique=True)),
                ("exam_name", models.CharField(max_length=255)),
                ("subject", models.CharField(blank=True, max_length=100, null=True)),
                ("school_year", models.IntegerField(blank=True, null=True)),
                ("total_questions", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Exame",
                "verbose_name_plural": "Exames",
                "db_table": "tb_exams",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TbQuestionCompetency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Questão-Competência",
                "verbose_name_plural": "Questões-Competências",
                "db_table": "tb_question_competency",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TbQuestions",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("question_number", models.IntegerField()),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "correct_answer",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "skill_assessed",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "difficulty_level",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "points",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Questão",
                "verbose_name_plural": "Questões",
                "db_table": "tb_questions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TbSchool",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("school", models.CharField(max_length=255)),
                (
                    "director_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Escola",
                "verbose_name_plural": "Escolas",
                "db_table": "tb_school",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TbSchoolIdebIndicators",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fiscal_year", models.BigIntegerField()),
                (
                    "ideb_target",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "regional_average",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "state_average",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "critical_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "actual_avg_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Indicador IDEB da Escola",
                "verbose_name_plural": "Indicadores IDEB das Escolas",
                "db_table": "tb_school_ideb_indicators",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TbStudentAnswers",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("answer_text", models.TextField(blank=True, null=True)),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                ("response_time_seconds", models.IntegerField(blank=True, null=True)),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Resposta do Aluno",
                "verbose_name_plural": "Respostas dos Alunos",
                "db_table": "tb_student_answers",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TbStudentDescriptorAchievements",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("achieved_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Conquista de Descritor",
                "verbose_name_plural": "Conquistas de Descritores",
                "db_table": "tb_student_descriptor_achievements",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TbStudentLearningProgress",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("score", models.DecimalField(decimal_places=2, max_digits=10)),
                ("max_score", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "descriptor_mastery",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("assessment_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Progresso de Aprendizagem",
                "verbose_name_plural": "Progressos de Aprendizagem",
                "db_table": "tb_student_learning_progress",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TbStudents",
            fields=[
                ("id_student", models.AutoField(primary_key=True, serialize=False)),
                ("student_serial", models.IntegerField(unique=True)),
                ("student_name", models.CharField(max_length=255)),
                ("enrollment_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="enrolled", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Aluno",
                "verbose_name_plural": "Alunos",
                "db_table": "tb_students",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TbSubject",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("subject_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Disciplina",
                "verbose_name_plural": "Disciplinas",
                "db_table": "tb_subject",
                "ordering": ["subject_name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TbTeacher",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("teacher_serial", models.BigIntegerField(unique=True)),
                ("teacher_name", models.CharField(max_length=255)),
                ("status", models.CharField(default="active", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Professor",
                "verbose_name_plural": "Professores",
                "db_table": "tb_teacher",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TbTeacherSchool",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("assignment_date", models.DateField()),
                ("status", models.CharField(default="active", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Professor-Escola",
                "verbose_name_plural": "Professores-Escolas",
                "db_table": "tb_teacher_school",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TbTeacherSubject",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Professor-Disciplina",
                "verbose_name_plural": "Professores-Disciplinas",
                "db_table": "tb_teacher_subject",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TbQuestionDescriptor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_descriptor",
                    models.ForeignKey(
                        db_column="id_descriptor",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="students.tbdescriptorscatalog",
                    ),
                ),
                (
                    "id_question",
                    models.ForeignKey(
                        db_column="id_question",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="students.tbquestions",
                    ),
                ),
            ],
            options={
                "db_table": "tb_question_descriptor",
                "managed": True,
            },
        ),
    ]
