# Generated by Django 5.2.7 on 2025-11-25 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tbalternatives",
            options={
                "managed": False,
                "ordering": ["id_question", "alternative_order"],
                "verbose_name": "Alternativa",
                "verbose_name_plural": "Alternativas",
            },
        ),
    ]
