# Generated by Django 5.2.7 on 2026-01-07 17:01

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("students", "0002_add_exam_file_column"),
    ]

    operations = [
        migrations.CreateModel(
            name="TbMunicipalFinancial",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fiscal_year", models.IntegerField(unique=True)),
                (
                    "orcamento_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "orcamento_executado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "fundeb_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "fnde_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "recursos_proprios",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "outras_receitas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "percentual_mde",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "custo_aluno_ano",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Financeiro Municipal",
                "verbose_name_plural": "Financeiro Municipal",
                "db_table": "tb_municipal_financial",
                "ordering": ["-fiscal_year"],
                "managed": True,
            },
        ),
        migrations.AlterModelOptions(
            name="tbalternatives",
            options={
                "managed": False,
                "ordering": ["id_question", "alternative_order"],
                "verbose_name": "Alternativa",
                "verbose_name_plural": "Alternativas",
            },
        ),
        migrations.AlterModelOptions(
            name="tbclass",
            options={
                "managed": False,
                "ordering": ["-created_at", "class_name"],
                "verbose_name": "Turma",
                "verbose_name_plural": "Turmas",
            },
        ),
        migrations.AlterModelOptions(
            name="tbexams",
            options={
                "managed": False,
                "ordering": ["-created_at", "exam_name"],
                "verbose_name": "Exame",
                "verbose_name_plural": "Exames",
            },
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("gestor", "Gestor"),
                            ("coordenador", "Coordenador"),
                            ("administrador", "Administrador"),
                            ("gerente", "Gerente"),
                        ],
                        default="gestor",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        db_column="city_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="students.tbcity",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
                "db_table": "custom_user",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="TbAlert",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("frequencia", "Frequencia"),
                            ("desempenho", "Desempenho"),
                            ("infraestrutura", "Infraestrutura"),
                            ("financeiro", "Financeiro"),
                            ("docente", "Corpo Docente"),
                            ("fluxo", "Fluxo Escolar"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severidade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                            ("critica", "Critica"),
                        ],
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("data_geracao", models.DateTimeField(auto_now_add=True)),
                ("data_resolucao", models.DateTimeField(blank=True, null=True)),
                ("resolvido", models.BooleanField(default=False)),
                (
                    "id_school",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_school",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="students.tbschool",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta",
                "verbose_name_plural": "Alertas",
                "db_table": "tb_alert",
                "ordering": ["-data_geracao"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TbSchoolGeolocation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("latitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=7, max_digits=10)),
                (
                    "zona",
                    models.CharField(
                        choices=[("urbana", "Urbana"), ("rural", "Rural")],
                        default="urbana",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_school",
                    models.OneToOneField(
                        db_column="id_school",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geolocation",
                        to="students.tbschool",
                    ),
                ),
            ],
            options={
                "verbose_name": "Geolocalizacao da Escola",
                "verbose_name_plural": "Geolocalizacoes das Escolas",
                "db_table": "tb_school_geolocation",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TbSchoolInfrastructure",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("num_salas", models.IntegerField(default=0)),
                ("num_laboratorios", models.IntegerField(default=0)),
                ("tem_biblioteca", models.BooleanField(default=False)),
                ("tem_quadra", models.BooleanField(default=False)),
                ("tem_quadra_coberta", models.BooleanField(default=False)),
                ("tem_refeitorio", models.BooleanField(default=False)),
                ("tem_auditorio", models.BooleanField(default=False)),
                ("tem_sala_leitura", models.BooleanField(default=False)),
                ("tem_sala_professores", models.BooleanField(default=False)),
                ("tem_sala_atendimento", models.BooleanField(default=False)),
                ("tem_internet", models.BooleanField(default=False)),
                (
                    "tipo_internet",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "velocidade_internet_mbps",
                    models.IntegerField(blank=True, null=True),
                ),
                ("num_computadores", models.IntegerField(default=0)),
                ("num_tablets", models.IntegerField(default=0)),
                ("tem_projetor", models.BooleanField(default=False)),
                ("num_projetores", models.IntegerField(default=0)),
                ("tem_acessibilidade", models.BooleanField(default=False)),
                ("tem_rampa", models.BooleanField(default=False)),
                ("tem_banheiro_pcd", models.BooleanField(default=False)),
                ("tem_piso_tatil", models.BooleanField(default=False)),
                ("tem_elevador", models.BooleanField(default=False)),
                ("tem_agua_potavel", models.BooleanField(default=True)),
                ("tem_energia", models.BooleanField(default=True)),
                ("tem_esgoto", models.BooleanField(default=True)),
                ("tem_coleta_lixo", models.BooleanField(default=True)),
                (
                    "estado_conservacao",
                    models.CharField(
                        choices=[
                            ("otimo", "Otimo"),
                            ("bom", "Bom"),
                            ("regular", "Regular"),
                            ("ruim", "Ruim"),
                            ("critico", "Critico"),
                        ],
                        default="bom",
                        max_length=20,
                    ),
                ),
                ("ultima_reforma", models.DateField(blank=True, null=True)),
                ("necessita_reforma", models.BooleanField(default=False)),
                ("areas_reforma", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_school",
                    models.OneToOneField(
                        db_column="id_school",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="infrastructure",
                        to="students.tbschool",
                    ),
                ),
            ],
            options={
                "verbose_name": "Infraestrutura da Escola",
                "verbose_name_plural": "Infraestruturas das Escolas",
                "db_table": "tb_school_infrastructure",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TbStudentProfile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("data_nascimento", models.DateField(blank=True, null=True)),
                (
                    "genero",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("masculino", "Masculino"),
                            ("feminino", "Feminino"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "raca_cor",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("branca", "Branca"),
                            ("preta", "Preta"),
                            ("parda", "Parda"),
                            ("amarela", "Amarela"),
                            ("indigena", "Indigena"),
                            ("nao_declarada", "Nao Declarada"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("tem_deficiencia", models.BooleanField(default=False)),
                (
                    "tipo_deficiencia",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("necessita_aee", models.BooleanField(default=False)),
                ("bolsa_familia", models.BooleanField(default=False)),
                (
                    "nivel_socioeconomico",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("muito_baixo", "Muito Baixo"),
                            ("baixo", "Baixo"),
                            ("medio_baixo", "Medio-Baixo"),
                            ("medio", "Medio"),
                            ("medio_alto", "Medio-Alto"),
                            ("alto", "Alto"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("utiliza_transporte_escolar", models.BooleanField(default=False)),
                (
                    "distancia_escola_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "zona_residencia",
                    models.CharField(
                        choices=[("urbana", "Urbana"), ("rural", "Rural")],
                        default="urbana",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_student",
                    models.OneToOneField(
                        db_column="id_student",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="students.tbstudents",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil do Aluno",
                "verbose_name_plural": "Perfis dos Alunos",
                "db_table": "tb_student_profile",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TbTeacherProfile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "escolaridade",
                    models.CharField(
                        choices=[
                            ("medio", "Ensino Medio"),
                            ("graduacao", "Graduacao"),
                            ("especializacao", "Especializacao"),
                            ("mestrado", "Mestrado"),
                            ("doutorado", "Doutorado"),
                        ],
                        default="graduacao",
                        max_length=50,
                    ),
                ),
                (
                    "formacao_area",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("formacao_continuada", models.BooleanField(default=False)),
                (
                    "tipo_contrato",
                    models.CharField(
                        choices=[
                            ("efetivo", "Efetivo"),
                            ("temporario", "Temporario"),
                            ("clt", "CLT"),
                        ],
                        default="efetivo",
                        max_length=50,
                    ),
                ),
                ("carga_horaria", models.IntegerField(default=40)),
                ("data_nascimento", models.DateField(blank=True, null=True)),
                ("genero", models.CharField(blank=True, max_length=20, null=True)),
                ("anos_experiencia", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_teacher",
                    models.OneToOneField(
                        db_column="id_teacher",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="students.tbteacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil do Professor",
                "verbose_name_plural": "Perfis dos Professores",
                "db_table": "tb_teacher_profile",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TbClassAttendanceSummary",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year_month", models.CharField(max_length=7)),
                ("school_days", models.IntegerField(default=0)),
                ("total_presences", models.IntegerField(default=0)),
                ("total_absences", models.IntegerField(default=0)),
                ("total_justified", models.IntegerField(default=0)),
                (
                    "attendance_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_class",
                    models.ForeignKey(
                        db_column="id_class",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_summaries",
                        to="students.tbclass",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resumo de Frequencia da Turma",
                "verbose_name_plural": "Resumos de Frequencia das Turmas",
                "db_table": "tb_class_attendance_summary",
                "managed": True,
                "unique_together": {("id_class", "year_month")},
            },
        ),
        migrations.CreateModel(
            name="TbSchoolFinancial",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fiscal_year", models.IntegerField()),
                (
                    "orcamento_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "orcamento_executado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "despesa_pessoal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "despesa_material",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "despesa_manutencao",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "despesa_alimentacao",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "despesa_transporte",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "despesa_equipamentos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "despesa_outros",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "fundeb_recebido",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "pdde_recebido",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "outras_receitas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_school",
                    models.ForeignKey(
                        db_column="id_school",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_records",
                        to="students.tbschool",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dados Financeiros da Escola",
                "verbose_name_plural": "Dados Financeiros das Escolas",
                "db_table": "tb_school_financial",
                "ordering": ["-fiscal_year"],
                "managed": True,
                "unique_together": {("id_school", "fiscal_year")},
            },
        ),
        migrations.CreateModel(
            name="TbSchoolFlowIndicators",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fiscal_year", models.IntegerField()),
                (
                    "etapa",
                    models.CharField(
                        choices=[
                            ("anos_iniciais", "Anos Iniciais"),
                            ("anos_finais", "Anos Finais"),
                            ("eja", "EJA"),
                        ],
                        max_length=50,
                    ),
                ),
                ("total_matriculas", models.IntegerField(default=0)),
                ("total_aprovados", models.IntegerField(default=0)),
                ("total_reprovados", models.IntegerField(default=0)),
                ("total_abandono", models.IntegerField(default=0)),
                ("total_transferidos", models.IntegerField(default=0)),
                (
                    "taxa_aprovacao",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "taxa_reprovacao",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "taxa_abandono",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "distorcao_idade_serie",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_school",
                    models.ForeignKey(
                        db_column="id_school",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flow_indicators",
                        to="students.tbschool",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicador de Fluxo Escolar",
                "verbose_name_plural": "Indicadores de Fluxo Escolar",
                "db_table": "tb_school_flow_indicators",
                "ordering": ["-fiscal_year"],
                "managed": True,
                "unique_together": {("id_school", "fiscal_year", "etapa")},
            },
        ),
        migrations.CreateModel(
            name="TbStudentAttendance",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("attendance_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("presente", "Presente"),
                            ("ausente", "Ausente"),
                            ("justificado", "Falta Justificada"),
                            ("atrasado", "Atrasado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("justification", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_class",
                    models.ForeignKey(
                        db_column="id_class",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="students.tbclass",
                    ),
                ),
                (
                    "id_student",
                    models.ForeignKey(
                        db_column="id_student",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="students.tbstudents",
                    ),
                ),
            ],
            options={
                "verbose_name": "Frequencia do Aluno",
                "verbose_name_plural": "Frequencias dos Alunos",
                "db_table": "tb_student_attendance",
                "ordering": ["-attendance_date"],
                "managed": True,
                "unique_together": {("id_student", "attendance_date")},
            },
        ),
    ]
